FROM openjdk:21-jdk-slim
WORKDIR /app
COPY target/*.jar app.jar

ARG SPRING_PROFILES_ACTIVE=dev
ENV SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]