name: Deploy to Render

on:
  push:
    branches:
      - main  
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t todo-api:dev .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  
        token: ${{ secrets.DOCKER_TOKEN }}   

    - name: Push Docker image to Docker Hub
      run: |
        docker push tharos02/todo-api:dev

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Install Render CLI
      run: |
        curl -fsSL https://render.com/deploy.sh | bash  

    - name: Log in to Render
      run: |
        render login --token ${{ secrets.RENDER_API_TOKEN }}  

    - name: Deploy Docker image to Render
      run: |
        render deploy --service spring-todo-api --docker tharos02/todo-api:dev

