name: Deploy to Render

on:
  push:
    branches:
      - main  
      
jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup docker (missing on MacOS)
      if: runner.os == 'macos'
      run: |
        brew install docker
        colima start
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/todo-api:dev
        build-args: |
          SPRING_PROFILES_ACTIVE=dev
        platforms: linux/amd64

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Install Render CLI
      run: |
        curl -L https://github.com/render-oss/cli/releases/download/v1.1.0/cli_1.1.0_linux_amd64.zip -o render.zip  
        unzip render.zip  
        sudo mv cli_v1.1.0 /usr/local/bin/render  

    - name: Trigger deploy with Render CLI
      run: |
        export RENDER_API_KEY=${{ secrets.RENDER_API_TOKEN }}
        render workspace set ${{ secrets.WORKSPACE_ID }} --output json -o json
        render deploys create ${{ secrets.SERVICE_ID }} --image docker.io/${{ secrets.DOCKER_USERNAME }}/todo-api:dev --wait --confirm --output json -o json
