name: Deploy to Render

on:
  push:
    branches:
      - main  
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Create application-dev.properties
      run: |
        mkdir -p src/main/resources
        echo "application.security.jwt.expiration=${{ secrets.JWT_EXPIRATION }}" > src/main/resources/application-dev.properties
        echo "application.security.jwt.secret-key=${{ secrets.JWT_SECRET_KEY }}" >> src/main/resources/application-dev.properties
        echo "spring.datasource.url=${{ secrets.DATABASE_URL }}" >> src/main/resources/application-dev.properties
        echo "spring.datasource.username=${{ secrets.DATABASE_USERNAME }}" >> src/main/resources/application-dev.properties
        echo "spring.datasource.password=${{ secrets.DATABASE_PASSWORD }}" >> src/main/resources/application-dev.properties
        echo "spring.jpa.hibernate.ddl-auto=update" >> src/main/resources/application-dev.properties
        echo "spring.jpa.show-sql=true" >> src/main/resources/application-dev.properties
        echo "spring.jpa.properties.hibernate.format_sql=true" >> src/main/resources/application-dev.properties
        echo "spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect" >> src/main/resources/application-dev.properties
        echo "spring.application.name=Todo" >> src/main/resources/application-dev.properties

    - name: Show current directory
      run: pwd
    
    - name: List files in current directory
      run: ls -la
    
    - name: Show content of application-dev.properties
      run: cat application-dev.properties

    - name: Build Docker image
      run: |
        docker build --build-arg SPRING_PROFILES_ACTIVE=dev --platform=linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/todo-api:dev .
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  
        password: ${{ secrets.DOCKER_TOKEN }}   

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/todo-api:dev
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Install Render CLI
      run: |
        curl -L https://github.com/render-oss/cli/releases/download/v1.1.0/cli_1.1.0_linux_amd64.zip -o render.zip  
        unzip render.zip  
        sudo mv cli_v1.1.0 /usr/local/bin/render  
    - name: Trigger deploy with Render CLI
      run: |
        export RENDER_API_KEY=${{ secrets.RENDER_API_TOKEN }}
        render workspace set ${{ secrets.WORKSPACE_ID }} --output json -o json
        render deploys create ${{ secrets.SERVICE_ID }} --image docker.io/${{ secrets.DOCKER_USERNAME }}/todo-api:dev --wait --confirm --output json -o json
