name: Deploy to Render

on:
  push:
    branches:
      - main  
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t tharos02/todo-api:dev .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  
        password: ${{ secrets.DOCKER_TOKEN }}   

    - name: Push Docker image to Docker Hub
      run: |
        docker push tharos02/todo-api:dev

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Install Render CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/render-oss/cli/refs/heads/main/bin/install.sh | sh
        
    - name: Log in to Render
      run: |
        export RENDER_API_TOKEN=${{ secrets.RENDER_API_TOKEN }}  # Setzt den Render API-Token als Umgebungsvariable
        render login  

    - name: Deploy Docker image to Render
      run: |
        render deploy --service spring-todo-api --docker tharos02/todo-api:dev  
        echo "Deployment to Render completed successfully"  
